spring:
  application.name: jooqtest

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:

  flyway:
    locations: /db/migrations
    table: flyway_schema_history
    enabled: true
logging:
  level:
    org.jooq.tools.LoggerListener: DEBUG
    org.jooq.tools.LoggerListener.jooq: TRACE
    org.jooq: DEBUG